---
- hosts: 127.0.0.1
  become: yes
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  
  tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages to the latest version
      apt:
        upgrade: dist

    - name: Add Vagrant apt repository key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Vagrant apt repository
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
        state: present
        update_cache: yes

    - name: Add Docker apt repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: yes

    - name: Install packages
      apt:
        pkg: "{{ packages_tm }}"
        state: present

    - name: Clone oh-my-zsh repo
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh.git
        dest=/home/{{ user }}/.oh-my-zsh
        
    - name: Copy .zshrc
      template:
        src: "templates/zshrc"
        dest: "/home/{{user}}/.zshrc"
        owner: "{{user}}"
        group: "{{user}}"
        force: no
    
    - name: Set proper ownership of oh-my-zsh files
      file:
        path: "/home/{{user}}/.oh-my-zsh"
        owner: "{{user}}"
        group: "{{user}}"
        recurse: yes

    - name: Set zsh as default shell
      user:
        name={{ user }}
        shell=/bin/zsh

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
        
    - name: Add the user to docker group
      user:
        name: "{{ user }}"
        group: docker

